### ISSUE TITLE
SYSTEMD file to start as a service?

### ISSUE THREAD

**Issue by brimur** [Barracuda09/SATPI#66]
I have tried to start SatPI as a service but I am failing. There is something hard coded so that it will only run with relative paths. i.e if I run it as /opt/satPI/satPI then it will not run properly. I have to... cd /opt/satPI and then run it as ./satPI. 

Starting the daemon using /opt/saPI/satPI I have tried adding the app and http as parameters but the tuners still do not show up in my TVHeadend server and the web page on 8875 does not load.

Have you created a service file yourself that works? Can you share it?

Thanks

**Comment by Barracuda09** [comment]
Hi,

No I have not made an service file myself, I will look into this as the web path seems indeed broken

**Comment by Barracuda09** [comment]
Hi,

The problem is that the XML settings file is overriding the command options.

So the quick fix would be to delete the SatPI.xml file and try again. I will try to fix this as soon as possible. And I use this to test start SatPI:

``
/usr/satpi/satpi --no-daemon --http-path /usr/satpi/web
``

Thanks for giving this a trying

**Comment by brimur** [comment]
A little late, sorry, but using the above it is running as a service fine now. Thanks
